Repository GooseMoment/Peak, pull requests merged in 2024-11, with the labels that each got.

#280 TaskSimpleCreate: 디렉터리 이동 및 중복 생성 해결
  frontend/src/components/drawers/Drawer.jsx
  frontend/src/components/project/Creates/utils/addDateFromToday.js
  frontend/src/components/project/TaskCreateSimple/CreateSimpleBox.jsx
  frontend/src/components/project/TaskCreateSimple/SimpleAssigned.jsx
  frontend/src/components/project/TaskCreateSimple/SimpleDue.jsx
  frontend/src/components/project/TaskCreateSimple/SimplePriority.jsx
  frontend/src/components/project/TaskCreateSimple/addDateFromToday.js
  frontend/src/components/project/TaskCreateSimple/index.jsx
Labels: 프론트엔드, 기능 개선

#281 TaskDetail과 TaskCreate 컴포넌트 수정 + #176
  backend/notifications/views.py
  backend/tasks/views.py
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/api/notifications.api.js
  frontend/src/api/tasks.api.js
  frontend/src/components/project/TaskCreateSimple/index.jsx
  frontend/src/components/project/taskDetails/Contents.jsx
  frontend/src/components/project/taskDetails/Memo.jsx
  frontend/src/components/project/taskDetails/Reminder.jsx
  frontend/src/components/project/taskDetails/ReminderContents.jsx
  frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
  frontend/src/components/project/taskDetails/TaskCreate.jsx
  frontend/src/components/project/taskDetails/TaskCreateElement.jsx
  frontend/src/components/project/taskDetails/TaskDetail.jsx
  frontend/src/components/project/taskDetails/TaskDetailElement.jsx
  frontend/src/components/tasks/TaskNameInput.jsx
  frontend/src/components/tasks/utils/taskDate.jsx
  frontend/src/pages/ProjectPage.jsx
Labels: 백엔드, 프론트엔드, 기능 개선

#265 Navbar: iOS에서 항목 터치 시 항목이 깜빡거리는 현상 해결
  frontend/src/components/navbar/Navbar.jsx
Labels: 프론트엔드, 버그 수정

#271 HomePage, Announcements 추가
  backend/announcements/__init__.py
  backend/announcements/admin.py
  backend/announcements/apps.py
  backend/announcements/migrations/0001_initial.py
  backend/announcements/migrations/__init__.py
  backend/announcements/models.py
  backend/announcements/serializers.py
  backend/announcements/signals.py
  backend/announcements/tests.py
  backend/announcements/urls.py
  backend/announcements/views.py
  backend/django_peak/settings.py
  backend/django_peak/urls.py
  backend/requirements.txt
  backend/tasks/serializers.py
  backend/tasks/views.py
  backend/today/urls.py
  backend/today/views.py
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/global.css
  frontend/public/images/safari.webp
  frontend/public/locales/en/docs.json
  frontend/public/locales/en/home.json
  frontend/public/locales/ko/docs.json
  frontend/public/locales/ko/home.json
  frontend/src/api/announcements.api.js
  frontend/src/api/today.api.js
  frontend/src/assets/home/PlusCircle.jsx
  frontend/src/assets/themes.js
  frontend/src/components/announcements/HeartButton.jsx
  frontend/src/components/common/PageBack.jsx
  frontend/src/components/common/PageDescription.jsx
  frontend/src/components/common/PageTitle.jsx
  frontend/src/components/home/AddTask.jsx
  frontend/src/components/home/Announcements.jsx
  frontend/src/components/home/AssignedToday.jsx
  frontend/src/components/home/Header.jsx
  frontend/src/components/home/InstallPeak.jsx
  frontend/src/components/home/Module.jsx
  frontend/src/components/home/VGraph.jsx
  frontend/src/containers/DocsLayout.jsx
  frontend/src/pages/AnnouncementDetailPage.jsx
  frontend/src/pages/AnnouncementListPage.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/docs/InstallInstructionPage.jsx
  frontend/src/routers/mainRouter.jsx
Labels: 백엔드, 프론트엔드, 새 기능, migrate 필요
