Repository GooseMoment/Peak, pull requests merged in 2024-09, with the labels that each got.

#226 TodayPage 추가
  backend/tasks/serializers.py
  backend/tasks/urls.py
  backend/tasks/views.py
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/api/tasks.api.js
  frontend/src/components/common/CollapseButton.jsx
  frontend/src/components/drawers/DrawerIcons.jsx
  frontend/src/components/project/skeletons/SkeletonTodayPage.jsx
  frontend/src/components/tasks/Task.jsx
  frontend/src/components/tasks/TaskFrame.jsx
  frontend/src/pages/TodayPage.jsx
Labels: 프론트엔드, 새 기능

#233 Sidebar: SidebarContext 추가, SidebarLink 리팩토링 & 로그아웃 버튼 로딩 추가
  frontend/src/components/sidebar/ConfirmationSignOut.jsx
  frontend/src/components/sidebar/Footer.jsx
  frontend/src/components/sidebar/Header.jsx
  frontend/src/components/sidebar/Middle.jsx
  frontend/src/components/sidebar/Sidebar.jsx
  frontend/src/components/sidebar/SidebarContext.jsx
  frontend/src/components/sidebar/SidebarLink.jsx
  frontend/src/containers/AppLayout.jsx
  frontend/src/containers/Layout.jsx
Labels: 프론트엔드, 기능 개선

#246 번역: 어색한 문장 수정 & ImageCropper 버튼 번역 추가
  frontend/public/locales/en/settings.json
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/settings.json
  frontend/public/locales/ko/translation.json
  frontend/src/components/settings/ImageCropper.jsx
Labels: 프론트엔드, 기능 개선

#216 Task Simple Create 추가
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/components/drawers/Drawer.jsx
  frontend/src/components/project/Creates/simple/CreateSimpleBox.jsx
  frontend/src/components/project/Creates/simple/SimpleAssigned.jsx
  frontend/src/components/project/Creates/simple/SimpleDue.jsx
  frontend/src/components/project/Creates/simple/SimplePriority.jsx
  frontend/src/components/project/Creates/simple/TaskCreateSimple.jsx
  frontend/src/components/project/Creates/utils/addDateFromToday.js
  frontend/src/components/project/taskDetails/Drawer.jsx
  frontend/src/components/project/taskDetails/TaskCreate.jsx
  frontend/src/components/project/taskDetails/TaskDetail.jsx
  frontend/src/components/tasks/TaskCircle.jsx
  frontend/src/components/tasks/TaskNameInput.jsx
Labels: 프론트엔드, 새 기능

#244 Button의 prop 이름에서 $ 기호를 제거
  frontend/src/components/common/Button.jsx
  frontend/src/components/common/DeleteAlert.jsx
  frontend/src/components/settings/ImageCropper.jsx
  frontend/src/components/settings/PasswordSection.jsx
  frontend/src/components/settings/UnblockButton.jsx
  frontend/src/components/sidebar/ConfirmationSignOut.jsx
  frontend/src/components/sign/forms.jsx
  frontend/src/components/users/FollowButton.jsx
  frontend/src/components/users/Requests.jsx
  frontend/src/pages/settings/Account.jsx
  frontend/src/pages/settings/Notifications.jsx
Labels: 프론트엔드, 기능 개선

#252 Task 드래그 앤 드롭 추가
  backend/drawers/signals.py
  backend/drawers/utils.py
  backend/drawers/views.py
  backend/tasks/admin.py
  backend/tasks/apps.py
  backend/tasks/migrations/0013_task_order.py
  backend/tasks/models.py
  backend/tasks/serializers.py
  backend/tasks/signals.py
  backend/tasks/views.py
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/drawers/Drawer.jsx
  frontend/src/components/intro/DemoBlurb.jsx
  frontend/src/components/intro/DemoDrawer.jsx
  frontend/src/components/project/dragAndDown/DragAndDownBox.jsx
  frontend/src/components/project/skeletons/SkeletonProjectPage.jsx
  frontend/src/components/social/logDetails/DrawerBundle.jsx
  frontend/src/components/tasks/TaskFrame.jsx
Labels: 새 기능, migrate 필요

#242 FollowButton: 언팔로우 전에 확인하기
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/components/users/FollowButton.jsx
Labels: 프론트엔드, 기능 개선

#256 새로운 모바일 Navbar
  frontend/src/assets/themes.js
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/components/sidebar/Header.jsx
  frontend/src/components/sidebar/Middle.jsx
  frontend/src/components/sidebar/Sidebar.jsx
  frontend/src/components/sidebar/SidebarContext.jsx
  frontend/src/components/sidebar/SidebarLink.jsx
  frontend/src/containers/Layout.jsx
Labels: 프론트엔드, 기능 개선

#262 Task: 모든 요소가 드래그되도록 수정
  frontend/src/components/project/dragAndDown/DragAndDownBox.jsx
  frontend/src/components/tasks/Priority.jsx
  frontend/src/components/tasks/TaskFrame.jsx
Labels: 프론트엔드, 버그 수정

#264 TimezoneMixin 추가 & Today 날짜가 시간대를 고려함
  backend/api/mixins.py
  backend/api/utils.py
  backend/api/views.py
  backend/django_peak/settings.py
  backend/drawers/views.py
  backend/projects/views.py
  backend/tasks/admin.py
  backend/tasks/views.py
  backend/today/views.py
  frontend/src/api/client.js
  frontend/src/api/today.api.js
  frontend/src/pages/TodayPage.jsx
  frontend/src/utils/clientSettings.jsx
Labels: 백엔드, 프론트엔드, 새 기능, 기능 개선
