Repository GooseMoment/Peak, pull requests merged in 2024-10, with the labels that each got.

#245 Create docker-image.yml
  .github/workflows/docker-image.yml
Labels: 운영/개발 환경

#236 USER_DEFAULT_PROFILE_IMG 설정을 .env에 추가
  .env.example
  backend/django_peak/settings.py
Labels: 프론트엔드, 운영/개발 환경

#261 UserPage: 배너 스타일 수정 & 프로필 사진이 사라지던 문제 해결
  frontend/src/components/users/UserProfileHeader.jsx
Labels: 프론트엔드, 기능 개선

#263 ProjectListPage 생성버튼 추가+공개범위에 따른 아이콘 표시+SocialPage에서 Task 색상변경+Drawer 더보기 버튼 loading 옵션 추가
  frontend/src/components/drawers/Drawer.jsx
  frontend/src/components/drawers/DrawerBox.jsx
  frontend/src/components/project/common/PrivacyIcon.jsx
  frontend/src/components/social/logDetails/TaskBox.jsx
  frontend/src/components/tasks/TaskFrame.jsx
  frontend/src/components/tasks/utils/taskCalculation.jsx
  frontend/src/pages/ProjectListPage.jsx
  frontend/src/pages/ProjectPage.jsx
Labels: 프론트엔드, 기능 개선

#266 ProjectEdit과 DrawerEdit: Create와의 통합 및 리팩토링
  frontend/public/global.css
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/components/intro/DemoCheer.jsx
  frontend/src/components/project/Creates/DrawerCreate.jsx
  frontend/src/components/project/Creates/ProjectCreate.jsx
  frontend/src/components/project/ProjectName.jsx
  frontend/src/components/project/common/Middle.jsx
  frontend/src/components/project/common/Progress.jsx
  frontend/src/components/project/common/Title.jsx
  frontend/src/components/project/common/palettes.js
  frontend/src/components/project/edit/Color.jsx
  frontend/src/components/project/edit/DrawerEdit.jsx
  frontend/src/components/project/edit/EditBox.jsx
  frontend/src/components/project/edit/Middle.jsx
  frontend/src/components/project/edit/Privacy.jsx
  frontend/src/components/project/edit/ProjectEdit.jsx
  frontend/src/components/project/edit/ProjectType.jsx
  frontend/src/components/project/edit/TitleInput.jsx
  frontend/src/components/project/taskDetails/Drawer.jsx
  frontend/src/components/project/taskDetails/DrawerFolder.jsx
  frontend/src/components/project/taskDetails/Reminder.jsx
  frontend/src/components/project/taskDetails/ReminderContents.jsx
  frontend/src/components/sidebar/Middle.jsx
  frontend/src/components/social/logDetails/DrawerBundle.jsx
  frontend/src/components/social/logsPreview/LogPreviewBox.jsx
  frontend/src/components/users/ProjectList.jsx
  frontend/src/components/users/UserProfileHeader.jsx
  frontend/src/pages/ProjectListPage.jsx
  frontend/src/pages/ProjectPage.jsx
  frontend/src/pages/TodayPage.jsx
  frontend/src/pages/settings/Account.jsx
Labels: 프론트엔드, 기능 개선

#268 Task의 Due 수정 + #202 + #235
  backend/drawers/utils.py
  backend/notifications/utils.py
  backend/notifications/views.py
  backend/tasks/admin.py
  backend/tasks/migrations/0014_remove_task_due_time_remove_task_due_tz_and_more.py
  backend/tasks/migrations/0015_alter_task_due_type.py
  backend/tasks/migrations/0016_alter_task_due_type.py
  backend/tasks/models.py
  backend/tasks/serializers.py
  backend/tasks/utils.py
  backend/tasks/views.py
  backend/today/views.py
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/components/common/ContextMenu.jsx
  frontend/src/components/drawers/Drawer.jsx
  frontend/src/components/intro/DemoDrawer.jsx
  frontend/src/components/intro/DemoPlan.jsx
  frontend/src/components/project/Creates/simple/SimpleAssigned.jsx
  frontend/src/components/project/Creates/simple/SimpleDue.jsx
  frontend/src/components/project/Creates/simple/TaskCreateSimple.jsx
  frontend/src/components/project/Creates/utils/addDateFromToday.js
  frontend/src/components/project/common/BarChart.jsx
  frontend/src/components/project/common/PrivacyIcon.jsx
  frontend/src/components/project/due/QuickDue.jsx
  frontend/src/components/project/due/RepeatDetail.jsx
  frontend/src/components/project/due/TimeDetail.jsx
  frontend/src/components/project/taskDetails/Assigned.jsx
  frontend/src/components/project/taskDetails/Contents.jsx
  frontend/src/components/project/taskDetails/Drawer.jsx
  frontend/src/components/project/taskDetails/Due.jsx
  frontend/src/components/project/taskDetails/TaskCreate.jsx
  frontend/src/components/tasks/TaskFrame.jsx
  frontend/src/components/tasks/utils/taskCalculation.jsx
  frontend/src/components/tasks/utils/taskDate.jsx
  frontend/src/pages/TodayPage.jsx
Labels: 백엔드, 기능 개선

#269 Fix UserPage: 모바일에서의 프로젝트 목록 왼쪽 여백 감소 #267
  frontend/src/components/users/ProjectList.jsx
Labels: 프론트엔드, 기능 개선

#272 Toastify: 모바일 화면에서의 토스트 스타일 개선
  frontend/public/global.css
  frontend/src/assets/keyframes.js
  frontend/src/containers/Root.jsx
  frontend/src/utils/notify.js
Labels: 프론트엔드, 기능 개선

#273 TimezoneMixin: pytz를 zoneinfo로 변경
  backend/api/exceptions.py
  backend/api/mixins.py
  backend/notifications/views.py
  backend/requirements.txt
  backend/tasks/views.py
Labels: 백엔드, 버그 수정

#284 유저 팔로잉/팔로워 카운트 반영, 백엔드 권한 관련 함수 추가, FollowList 뷰 리팩토링 등
  backend/api/permissions.py
  backend/drawers/views.py
  backend/notifications/views.py
  backend/projects/views.py
  backend/social/permissions.py
  backend/social/signals.py
  backend/social/views.py
  backend/tasks/views.py
  backend/today/views.py
  backend/user_setting/views.py
  backend/users/urls.py
  backend/users/views.py
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/api/social.api.js
  frontend/src/api/users.api.js
  frontend/src/components/drawers/Drawer.jsx
  frontend/src/components/sign/forms.jsx
  frontend/src/components/social/logDetails/DrawerBundle.jsx
  frontend/src/components/users/FollowList.jsx
  frontend/src/components/users/FollowsCount.jsx
  frontend/src/components/users/ListUserProfile.jsx
  frontend/src/pages/SocialExplorePage.jsx
  frontend/src/pages/SocialFollowingPage.jsx
  frontend/src/pages/TodayPage.jsx
  frontend/src/pages/UserPage.jsx
  frontend/src/pages/settings/Blocks.jsx
  frontend/src/queries/queryClient.js
  frontend/src/utils/pagination.js
Labels: 백엔드, 프론트엔드, 기능 개선

#274 IntroPage: Invalid DateTime 등 해결
  frontend/src/components/intro/DemoBlurb.jsx
  frontend/src/components/intro/DemoCheer.jsx
  frontend/src/components/intro/DemoDrawer.jsx
  frontend/src/components/intro/DemoTask.jsx
  frontend/src/components/intro/todays.js
  frontend/src/components/social/logDetails/DrawerBundle.jsx
  frontend/src/components/tasks/Priority.jsx
Labels: 프론트엔드, 버그 수정

#279 SettingsPage: Select 너비 조정 & Account 여백 조정
  frontend/src/components/settings/Select.jsx
  frontend/src/pages/settings/Account.jsx
Labels: 프론트엔드, 기능 개선

#253 SearchPage 추가
  backend/django_peak/urls.py
  backend/search/urls.py
  backend/search/views.py
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/api/search.api.js
  frontend/src/assets/themes.js
  frontend/src/components/common/CommonCalendar.jsx
  frontend/src/components/search/CalendarModal.jsx
  frontend/src/components/search/FilterButton.jsx
  frontend/src/components/search/FilterGroup.jsx
  frontend/src/components/search/FilterInput.jsx
  frontend/src/components/search/SearchBar.jsx
  frontend/src/components/search/SearchResults.jsx
  frontend/src/components/social/explore/ExploreSearchBar.jsx
  frontend/src/pages/SearchPage.jsx
  frontend/src/pages/SocialExplorePage.jsx
Labels: 백엔드, 프론트엔드, 새 기능

#278 NotificationsPage: searchParam 추가 시 replace
  frontend/src/pages/NotificationsPage.jsx
Labels: 프론트엔드, 버그 수정

#260 백엔드 users 앱의 로그인 관련 함수를 peak_auth 앱으로 분리
  backend/django_peak/settings.py
  backend/django_peak/urls.py
  backend/peak_auth/__init__.py
  backend/peak_auth/admin.py
  backend/peak_auth/apps.py
  backend/peak_auth/locale/__init__.py
  backend/peak_auth/locale/en/__init__.py
  backend/peak_auth/locale/en/translation.py
  backend/peak_auth/locale/ko/__init__.py
  backend/peak_auth/locale/ko/translation.py
  backend/peak_auth/locale/translations.py
  backend/peak_auth/migrations/0001_initial.py
  backend/peak_auth/migrations/__init__.py
  backend/peak_auth/models.py
  backend/peak_auth/tests.py
  backend/peak_auth/urls.py
  backend/peak_auth/utils.py
  backend/peak_auth/views.py
  backend/users/admin.py
  backend/users/migrations/0015_remove_passwordrecoverytoken_user_and_more.py
  backend/users/models.py
  backend/users/urls.py
  backend/users/views.py
  frontend/src/api/auth.api.js
  frontend/src/api/users.api.js
  frontend/src/components/sign/forms.jsx
  frontend/src/routers/mainRouter.jsx
Labels: 백엔드, migrate 필요

#289 Social 번역, 모바일화 및 구조적 개선
  backend/social/serializers.py
  backend/social/urls.py
  backend/social/views.py
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/api/social.api.js
  frontend/src/components/social/SocialCalendar.jsx
  frontend/src/components/social/SocialPageTitle.jsx
  frontend/src/components/social/explore/ExploreFeed.jsx
  frontend/src/components/social/explore/ExploreSearchBar.jsx
  frontend/src/components/social/interaction/comment/CommentBox.jsx
  frontend/src/components/social/interaction/comment/CommentModal.jsx
  frontend/src/components/social/interaction/reaction/EmojiModal.jsx
  frontend/src/components/social/logDetails/DrawerBundle.jsx
  frontend/src/components/social/logDetails/LogDetails.jsx
  frontend/src/components/social/logDetails/Quote.jsx
  frontend/src/components/social/logsPreview/LogPreviewBox.jsx
  frontend/src/components/social/logsPreview/LogsPreview.jsx
  frontend/src/pages/SocialExplorePage.jsx
  frontend/src/pages/SocialFollowingPage.jsx
Labels: 백엔드, 프론트엔드, 새 기능, 기능 개선
