Repository GooseMoment/Peak, pull requests merged in 2025-02, with the labels that each got.

#286 프로덕션에서 django admin에 접근할 수 없던 문제 해결 & Actions: Caddyfile 포맷 검사 액션 추가
  .env.example
  .github/workflows/backend.yaml
  .github/workflows/caddy.yaml
  .github/workflows/docker-image.yaml
  docker-compose.prod.yaml
  docker-compose.yaml
  web/Caddyfile
  web/Caddyfile.prod
Labels: 버그 수정, 운영/개발 환경

#313 backend/Dockerfile의 환경변수 형식 수정
  backend/Dockerfile
Labels: 운영/개발 환경

#315 설정>계정: 이메일이 짤리던 문제 해결
  frontend/src/pages/settings/Account.jsx
Labels: 프론트엔드, 기능 개선

#301 docker-compose.yml 파일에 extra_hosts 설정 추가
  docker-compose.yaml
Labels: 운영/개발 환경

#309 리액션 알림에서 리액션을 한 유저의 유저네임 대신 내 유저네임을 표시하던 문제 해결
  backend/notifications/push.py
Labels: 백엔드, 버그 수정

#292 peak_auth: 커스텀 예외 추가 및 gaierror 예외 핸들링
  backend/api/exceptions.py
  backend/peak_auth/exceptions.py
  backend/peak_auth/locale/en/translation.py
  backend/peak_auth/locale/ko/translation.py
  backend/peak_auth/urls.py
  backend/peak_auth/utils.py
  backend/peak_auth/views.py
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/api/auth.api.js
Labels: 백엔드, 프론트엔드, 버그 수정, 기능 개선

#306 2단계 인증: TOTP(일회성 코드) 추가
  backend/django_peak/settings.py
  backend/peak_auth/admin.py
  backend/peak_auth/mails.py
  backend/peak_auth/migrations/0002_twofactorauthtoken_totpsecret_and_more.py
  backend/peak_auth/models.py
  backend/peak_auth/totp.py
  backend/peak_auth/urls.py
  backend/peak_auth/views.py
  backend/users/auth.py
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/locales/en/settings.json
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/settings.json
  frontend/public/locales/ko/translation.json
  frontend/src/api/auth.api.js
  frontend/src/components/settings/PasswordSection.jsx
  frontend/src/components/sign/forms.jsx
  frontend/src/pages/SettingsPage.jsx
  frontend/src/pages/settings/Account.jsx
  frontend/src/pages/settings/Security.jsx
  frontend/src/pages/settings/settings.jsx
  frontend/src/routers/settingsChildren.jsx
  frontend/src/routers/signChildren.jsx
Labels: 백엔드, 프론트엔드, 새 기능, migrate 필요

#317 랜덤 리뷰어 지정 액션 추가
  .github/workflows/reviewer.yaml
Labels: 운영/개발 환경

#318 eslint에 no-use-before-define 규칙 추가
  frontend/eslint.config.js
  frontend/src/pages/SocialExplorePage.jsx
Labels: 프론트엔드, 버그 수정, 운영/개발 환경

#324 TOTP 보안키를 textarea로 변경 외
  frontend/public/locales/en/settings.json
  frontend/public/locales/ko/settings.json
  frontend/src/components/settings/ProfileImg.jsx
  frontend/src/components/settings/Section.jsx
  frontend/src/components/sign/Input.jsx
  frontend/src/components/sign/Showcase.jsx
  frontend/src/components/social/SocialPageTitle.jsx
  frontend/src/pages/SettingsPage.jsx
  frontend/src/pages/settings/Security.jsx
Labels: 프론트엔드

#316 모바일용 정렬 뷰 추가
  frontend/src/components/common/ModalBottomSheet.jsx
  frontend/src/components/drawers/Drawer.jsx
  frontend/src/components/project/sorts/SortMenuMobile.jsx
  frontend/src/components/project/sorts/SortMenuSelector.jsx
  frontend/src/pages/ProjectPage.jsx
Labels: 프론트엔드, 새 기능

#323 로그아웃 버튼을 사이드바에서 설정으로 이동
  frontend/public/locales/en/settings.json
  frontend/public/locales/ko/settings.json
  frontend/src/components/settings/ConfirmationSignOut.jsx
  frontend/src/components/sidebar/Footer.jsx
  frontend/src/pages/settings/General.jsx
Labels: 프론트엔드, 기능 개선

#327 Specify random-reviewer-discord@v0.1.2
  .github/workflows/reviewer.yaml
Labels: 버그 수정, 운영/개발 환경

#330 Repeat 제거
  backend/tasks/admin.py
  backend/tasks/migrations/0017_remove_task_repeat_delete_repeat.py
  backend/tasks/models.py
  backend/tasks/serializers.py
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/assets/project/calendar/repeat.svg
  frontend/src/assets/project/repeat/everyday.svg
  frontend/src/assets/project/repeat/everymonth.svg
  frontend/src/assets/project/repeat/everyweek.svg
  frontend/src/assets/project/repeat/everyyear.svg
  frontend/src/assets/project/repeat/weekday.svg
  frontend/src/assets/project/repeat/weekend.svg
  frontend/src/components/project/due/RepeatDetail.jsx
  frontend/src/components/project/due/TimeDetail.jsx
  frontend/src/components/project/taskDetails/Assigned.jsx
  frontend/src/components/project/taskDetails/Due.jsx
  frontend/src/components/project/taskDetails/Repeat.jsx
Labels: 프론트엔드

#319 푸시 알림 종류 선택 기능 추가 & TypeScript 추가
  backend/notifications/exceptions.py
  backend/notifications/migrations/0015_webpushsubscription_excluded_types.py
  backend/notifications/models.py
  backend/notifications/push.py
  backend/notifications/serializers.py
  backend/notifications/urls.py
  backend/notifications/views.py
  frontend/.depcheckrc.yaml
  frontend/eslint.config.js
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/locales/en/settings.json
  frontend/public/locales/ko/settings.json
  frontend/src/api/notifications.api.js
  frontend/src/components/settings/CheckboxGroup.tsx
  frontend/src/pages/settings/Notifications.jsx
  frontend/src/utils/clientSettings.jsx
  frontend/src/utils/compareFn.ts
  frontend/tsconfig.json
Labels: 백엔드, 프론트엔드, 새 기능, migrate 필요

#333 Upgrade random-reviewer-discord to v0.2.1
  .github/workflows/reviewer.yaml
Labels: 새 기능, 기능 개선, 운영/개발 환경

#320 설정>정보의 날짜 표시 변경
  frontend/public/locales/en/settings.json
  frontend/public/locales/ko/settings.json
  frontend/src/pages/settings/Info.jsx
Labels: 프론트엔드, 기능 개선, 운영/개발 환경

#322 알림 페이지에 새로고침 추가
  frontend/src/components/common/PageTitle.jsx
  frontend/src/pages/NotificationsPage.jsx
Labels: 프론트엔드, 새 기능

#326 TodayPage 리펙토링 및 필터에 해당하는 작업들이 모두 없을 때 안보이게 설정
  backend/today/urls.py
  backend/today/views.py
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/api/today.api.js
  frontend/src/components/today/ImportantTasks.jsx
  frontend/src/components/today/TodayAssignmentTasks.jsx
  frontend/src/pages/TodayPage.jsx
Labels: 백엔드, 프론트엔드, 새 기능

#321 프론트엔드 빌드 액션 추가 & 도커 이미지가 올바르게 빌드되지 않던 문제 수정
  .github/workflows/backend.yaml
  .github/workflows/docker-image.yaml
  .github/workflows/frontend.yaml
  deploy/README.md
  deploy/compose-prod.ps1
  deploy/compose-prod.sh
  deploy/run-builder.ps1
  frontend/.depcheckrc.yaml
  frontend/Dockerfile
  frontend/README.md
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: 버그 수정, 운영/개발 환경

#340 설정: '계정'을 '프로필'로 개명 외 & Bump prettier@v3.5.2
  .github/workflows/frontend.yaml
  frontend/README.md
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/locales/en/settings.json
  frontend/public/locales/ko/settings.json
  frontend/src/components/common/Switch.jsx
  frontend/src/components/home/Header.jsx
  frontend/src/components/settings/ImageCropper.jsx
  frontend/src/components/settings/PasswordSection.jsx
  frontend/src/components/settings/Select.jsx
  frontend/src/components/sidebar/Footer.jsx
  frontend/src/components/users/UserProfileHeader.jsx
  frontend/src/pages/SettingsPage.jsx
  frontend/src/pages/settings/Profile.jsx
  frontend/src/pages/settings/settings.jsx
  frontend/src/routers/settingsChildren.jsx
Labels: 프론트엔드, 기능 개선, 운영/개발 환경

#331 프론트엔드 의존 패키지 업데이트 & dependabot 구성 추가
  .github/dependabot.yaml
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/global.css
  frontend/src/containers/Root.jsx
Labels: 프론트엔드, 운영/개발 환경

#335 테마, 번역, 버튼 타입화
  frontend/.prettierrc.js
  frontend/eslint.config.js
  frontend/jsconfig.json
  frontend/src/@types/i18next.d.ts
  frontend/src/@types/styled.d.ts
  frontend/src/assets/themes.ts
  frontend/src/components/common/Button.tsx
  frontend/src/components/settings/ConfirmationSignOut.jsx
  frontend/src/components/settings/ImageCropper.jsx
  frontend/src/components/settings/PasswordSection.jsx
  frontend/src/components/users/FollowButton.jsx
  frontend/src/components/users/Requests.jsx
  frontend/src/main.jsx
  frontend/src/pages/settings/Notifications.jsx
  frontend/src/pages/settings/Profile.jsx
  frontend/src/pages/settings/Security.jsx
  frontend/src/utils/i18n.ts
  frontend/tsconfig.json
Labels: 프론트엔드, 기능 개선

#336 Navbar의 transition이 처음에는 실행되지 않도록 수정
  frontend/src/components/navbar/Navbar.jsx
Labels: 프론트엔드, 버그 수정

#343 Palette 타입화 및 getPaletteColor로의 개명
  frontend/public/locales/en/translation.json
  frontend/public/locales/ko/translation.json
  frontend/src/@types/styled.d.ts
  frontend/src/assets/palettes.ts
  frontend/src/assets/themes.ts
  frontend/src/components/home/VGraph.jsx
  frontend/src/components/intro/DemoCheer.jsx
  frontend/src/components/project/ProjectName.jsx
  frontend/src/components/project/common/Progress.jsx
  frontend/src/components/project/edit/Color.jsx
  frontend/src/components/project/edit/ProjectEdit.jsx
  frontend/src/components/project/taskDetails/DrawerFolder.jsx
  frontend/src/components/search/SearchResults.jsx
  frontend/src/components/sidebar/Middle.jsx
  frontend/src/components/social/logDetails/LogDetails.jsx
  frontend/src/components/social/logsPreview/LogPreviewBox.jsx
  frontend/src/components/today/ImportantTasks.jsx
  frontend/src/components/today/TodayAssignmentTasks.jsx
  frontend/src/components/users/ProjectList.jsx
  frontend/src/components/users/UserProfileHeader.jsx
  frontend/src/pages/ProjectPage.jsx
  frontend/src/pages/settings/Profile.jsx
Labels: 프론트엔드

#337 PersistStorage 추가
  .github/dependabot.yaml
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/pages/NotificationsPage.jsx
  frontend/src/queries/queryClient.js
Labels: 프론트엔드, 새 기능

#359 IntroPage의 프로젝트 색상이 표시되지 않던 문제 해결
  frontend/src/components/common/Button.tsx
  frontend/src/components/common/PageTitle.tsx
  frontend/src/components/drawers/DrawerBox.tsx
  frontend/src/components/intro/DemoDrawer.jsx
  frontend/src/components/intro/DemoDrawer.tsx
  frontend/src/components/intro/DemoProject.tsx
Labels: 프론트엔드, 버그 수정

#364 중복된 getCursorFromURL과 getPageFromURL 제거
  frontend/src/components/social/logDetails/LogDetails.jsx
  frontend/src/pages/AnnouncementListPage.jsx
  frontend/src/pages/NotificationsPage.jsx
  frontend/src/pages/SearchPage.jsx
  frontend/src/utils/pagination.js
  frontend/src/utils/pagination.ts
Labels: 프론트엔드, 기능 개선

#338 홈에 푸시 알림 켜기 모듈 추가
  frontend/public/locales/en/home.json
  frontend/public/locales/ko/home.json
  frontend/src/components/home/AllowNotification.tsx
  frontend/src/components/home/InstallPeak.tsx
  frontend/src/components/home/Module.tsx
  frontend/src/pages/HomePage.tsx
Labels: 프론트엔드, 새 기능

#379 pagination 함수 인자 타입에 URL 추가
  frontend/src/utils/pagination.ts
Labels: 프론트엔드, 버그 수정
