Repository GooseMoment/Peak, pull requests merged in 2025-07, with the labels that each got.

#433 Drawer Drag and Drop 추가 및 Task Drag and Drop 수정
  backend/drawers/exceptions.py
  backend/drawers/serializers.py
  backend/drawers/signals.py
  backend/drawers/urls.py
  backend/drawers/utils.py
  backend/drawers/views.py
  backend/tasks/serializers.py
  backend/tasks/signals.py
  backend/tasks/urls.py
  backend/tasks/utils.py
  backend/tasks/views.py
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/api/drawers.api.js
  frontend/src/api/tasks.api.js
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ko/translation.json
  frontend/src/components/drawers/Drawer.jsx
  frontend/src/components/drawers/DrawerBox.tsx
  frontend/src/components/project/dragAndDown/DragAndDownBox.jsx
  frontend/src/components/tasks/DrawerTask.jsx
  frontend/src/pages/ProjectPage.jsx
Labels: 백엔드, 프론트엔드, 새 기능, 기능 개선

#492 소셜의 SimpleProfile를 클릭 시 유저페이지로 이동
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ko/translation.json
  frontend/src/components/common/PageBack.tsx
  frontend/src/components/common/PageTitle.tsx
  frontend/src/components/social/common/SimpleProfile.tsx
  frontend/src/components/social/logDetails/Quote.jsx
  frontend/src/components/social/logsPreview/LogPreviewBox.jsx
  frontend/src/pages/SocialDailyPage.jsx
  frontend/src/pages/SocialDailyPage.tsx
Labels: 프론트엔드, 기능 개선

#493 Bump random-reviewer-discord from 0.2.1 to 0.2.2
  .github/workflows/reviewer.yaml
Labels: dependencies

#498 소셜 모델을 프론트엔드에 추가 & NotificationsPage 타입화
  frontend/src/api/client.ts
  frontend/src/api/common.d.ts
  frontend/src/api/notifications.api.ts
  frontend/src/api/social.d.ts
  frontend/src/components/common/FilterButtonGroup.tsx
  frontend/src/components/intro/DemoTheme.tsx
  frontend/src/components/notifications/Avatar.tsx
  frontend/src/components/notifications/Box.jsx
  frontend/src/components/notifications/Box.tsx
  frontend/src/components/notifications/Content.tsx
  frontend/src/components/notifications/ContentDetail.tsx
  frontend/src/components/notifications/ContentTitle.jsx
  frontend/src/components/notifications/ContentTitle.tsx
  frontend/src/components/users/FollowList.tsx
  frontend/src/pages/NotificationsPage.tsx
  frontend/src/pages/settings/Notifications.tsx
Labels: 프론트엔드

#499 Project issue 수정
  backend/api/exceptions.py
  backend/drawers/exceptions.py
  backend/drawers/migrations/0005_drawer_constraint_drawer_name.py
  backend/drawers/models.py
  backend/drawers/views.py
  backend/notifications/views.py
  backend/projects/exceptions.py
  backend/projects/migrations/0007_project_constraint_project_name.py
  backend/projects/models.py
  backend/projects/signals.py
  backend/projects/views.py
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ko/translation.json
  frontend/src/components/drawers/Drawer.jsx
  frontend/src/components/project/edit/DrawerEdit.jsx
  frontend/src/components/project/edit/ProjectEdit.jsx
  frontend/src/components/project/skeletons/SkeletonProjectPage.jsx
  frontend/src/components/project/taskDetails/Contents.jsx
  frontend/src/components/project/taskDetails/Drawer.jsx
  frontend/src/components/project/taskDetails/DrawerFolder.jsx
  frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
  frontend/src/components/project/taskDetails/TaskCreate.jsx
  frontend/src/components/project/taskDetails/TaskDetail.jsx
  frontend/src/components/tasks/TaskCircle.jsx
  frontend/src/components/tasks/TaskFrame.jsx
Labels: 백엔드, 프론트엔드, 버그 수정, 기능 개선, migrate 필요
