Repository GooseMoment/Peak, pull requests merged in 2025-04, with the labels that each got.

#439 '설정>테마'에서 '시스템'이 없어졌던 문제 해결
  frontend/src/components/settings/Select.jsx
  frontend/src/components/settings/SettingSwitch.jsx
  frontend/src/pages/settings/Appearance.tsx
Labels: 프론트엔드, 버그 수정

#446 설정>프로필에서 유저네임 아래가 짤리는 문제 해결
  frontend/src/pages/settings/Profile.jsx
Labels: 프론트엔드, 버그 수정

#428 User 타입화 & UserPage: '차단하기' 추가 외
  frontend/src/@types/vite-env.d.ts
  frontend/src/api/client.ts
  frontend/src/api/social.api.js
  frontend/src/api/social.d.ts
  frontend/src/api/users.api.js
  frontend/src/api/users.api.ts
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ko/translation.json
  frontend/src/assets/menu.tsx
  frontend/src/components/common/Confirmation.tsx
  frontend/src/components/common/DeleteAlert.jsx
  frontend/src/components/common/ModalWindow.jsx
  frontend/src/components/errors/ErrorLayout.jsx
  frontend/src/components/project/common/OptionsMenu.jsx
  frontend/src/components/project/sorts/SortMenu.jsx
  frontend/src/components/settings/ConfirmationSignOut.jsx
  frontend/src/components/settings/TOTPSection.tsx
  frontend/src/components/users/Bio.tsx
  frontend/src/components/users/FollowButton.tsx
  frontend/src/components/users/FollowList.tsx
  frontend/src/components/users/FollowsCount.tsx
  frontend/src/components/users/ListUserProfile.tsx
  frontend/src/components/users/ProjectList.tsx
  frontend/src/components/users/Requests.tsx
  frontend/src/components/users/Section.tsx
  frontend/src/components/users/UserProfileHeader.jsx
  frontend/src/components/users/UserProfileHeader.tsx
  frontend/src/pages/UserPage.tsx
Labels: 프론트엔드, 버그 수정, 새 기능

#447 작업 생성 시 뜨던 405 에러 수정
  backend/notifications/urls.py
Labels: 버그 수정

#444 홈의 프로필 사진 로딩 조건을 isLoading으로 변경
  frontend/src/components/home/Header.tsx
Labels: 프론트엔드, 버그 수정

#422 프론트엔드에서 404 페이지가 표시되지 않던 문제 해결 & 에러페이지에 상세 에러 메시지 표시
  frontend/src/assets/errors/RoadSign.tsx
  frontend/src/components/errors/ErrorLayout.jsx
  frontend/src/components/errors/ErrorLayout.tsx
  frontend/src/components/sign/forms.jsx
  frontend/src/pages/ErrorPage.jsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/UserPage.tsx
  frontend/src/routers/mainRouter.tsx
Labels: 프론트엔드, 버그 수정

#404 모바일 화면에서 토스트가 띄워졌을 때 네비바가 눌리지 않는 문제 해결
  frontend/public/global.css
Labels: 프론트엔드, 버그 수정

#443 FilterButtonGroup 타입화 & 처음에는 transition이 실행되지 않도록 수정
  frontend/src/components/common/FilterButtonGroup.tsx
  frontend/src/components/intro/DemoTheme.tsx
Labels: 프론트엔드, 버그 수정

#416 vite-plugin-pwa로 Service Worker에 precache 추가
  frontend/.npmrc
  frontend/Dockerfile
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/app.webmanifest
  frontend/public/robots.txt
  frontend/public/service-worker.js
  frontend/pwa-assets.config.ts
  frontend/src/@types/vite-env.d.ts
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ko/translation.json
  frontend/src/containers/Root.jsx
  frontend/src/main.tsx
  frontend/src/registerSW.js
  frontend/src/sw.ts
  frontend/src/utils/useUpdatePrompt.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
  web/caddy.prod/Caddyfile
Labels: 프론트엔드, 새 기능

#435 clientSettings와 Notifications 임시 타입화 & 모든 알림 유형을 제외할 시 저장할 수 없도록
  backend/notifications/exceptions.py
  backend/notifications/views.py
  frontend/src/api/notifications.api.js
  frontend/src/api/notifications.api.ts
  frontend/src/components/common/ThemeProvider.tsx
  frontend/src/components/settings/CheckboxGroup.tsx
  frontend/src/pages/NotificationsPage.jsx
  frontend/src/pages/settings/Notifications.tsx
  frontend/src/utils/clientSettings.tsx
Labels: 백엔드, 프론트엔드, 새 기능

#461 액션의 pnpm 캐시 추가
  .github/workflows/frontend.yaml
Labels: 기능 개선, 운영/개발 환경

#403 DailyLog 디자인 수정
  frontend/src/assets/locales/en/docs.json
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ko/docs.json
  frontend/src/assets/locales/ko/translation.json
  frontend/src/assets/palettes.ts
  frontend/src/components/common/PageBack.jsx
  frontend/src/components/social/common/DateBar.jsx
  frontend/src/components/social/common/SimpleProfile.jsx
  frontend/src/components/social/logDetails/LogDetails.jsx
  frontend/src/components/social/logDetails/Quote.jsx
  frontend/src/components/social/logsPreview/LogPreviewBox.jsx
  frontend/src/components/social/logsPreview/LogsPreview.jsx
  frontend/src/pages/SocialDailyPage.jsx
  frontend/src/pages/SocialFollowingPage.jsx
  frontend/src/pages/chunks/SocialPages.jsx
  frontend/src/pages/docs/InstallInstructionPage.jsx
  frontend/src/routers/mainRouter.tsx
  frontend/src/utils/useScreenType.js
Labels: 프론트엔드, 새 기능, 기능 개선
